version: '3'
services:
  mysql1:
    image: mysql:8.0.24
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db_settings/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db_settings/mysql_data:/var/lib/mysql
      # 設定ファイル
      - ./db_settings/mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!change_on_password
      MYSQL_DATABASE: my_mysql
      MYSQL_USER: mysql_user1
      MYSQL_PASSWORD: User1Pass123!change_on_password
      TZ: 'Asia/Tokyo'
    command: --innodb-use-native-aio=0
    networks:
      - flask_and_mysql_net

  html_server:
    image: flask_and_mysql:latest
    ports:
      - "5000:80"
    environment:
      RUNNING_ENV: docker
    volumes:
      # logが格納されるdir
      - ./html_server/log:/app/html_server/log
    depends_on:
      - mysql1
    restart: always
    networks:
      - flask_and_mysql_net

networks:
  flask_and_mysql_net:
